server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:3307/microservices
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HOTEL-SERVICE

  config:
    import: configserver:http://localhost:8085


